IMAGE_NAME = "debian/stretch64"
N = 2
MASTER_IP = "192.168.0.200"
NODE_RANGE = 200
NET_SUBNET = "192.168.0."
NET_GW = "192.168.0.1"
NET_DNS = "192.168.0.15"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "libvirt" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network :public_network,
            :dev => "virbr0",
            :mode => "virtio",
            :type => "bridge",
            auto_config: false
        master.vm.hostname = "k8s-master"
        master.vm.provision "shell", run: "always" do |s|
          s.path  = "scripts/set-static-ip.sh"
          s.args    = [MASTER_IP, NET_GW, NET_DNS]
        end
        master.vm.provision :reload
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "MASTER_IP",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "k8s-node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network :public_network,
                :dev => "virbr0",
                :mode => "virtio",
                :type => "bridge",
                auto_config: false
            node.vm.hostname = "k8s-node-#{i}"
            node.vm.provision "shell", run: "always" do |s|
                s.path  = "scripts/set-static-ip.sh"
                s.args    = ["NET_SUBNET #{i} + NODE_RANGE", NET_GW, NET_DNS]
            end
            node.vm.provision :reload
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "NET_SUBNET#{i + NODE_RANGE}",
                }
            end
        end
    end
end